version: "3.8"

services:
  python-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:4000"
    environment:
      - TZ=America/Santiago
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
